<?php

use Illuminate\Database\Seeder;

use \Carbon\Carbon;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	foreach ($this->members() as $key => $row) {
    		DB::table('members')->insert([
	            'user_id' => 1,
	            'name' => $row['name'],
	            'local_name' => $row['local_name']??null,
                'dob' => $row['dob']??Carbon::now(),
	            'chinese_zodiac' => $row['chinese_zodiac']??null,
	        ]);
    	}

        DB::table('relation')->insert([
            'member_id' => 2,
            'parent_id' => 1,
            'spouse' => 1,
        ]);
        DB::table('relation')->insert([
            'member_id' => 3,
            'parent_id' => 1,
            'spouse' => 0,
        ]);
    }

    protected function members()
    {
    	return [
    		['name'=>'Lee Soon Hoey','local_name'=>'李(顺火)','dob'=>'1916-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Goey Mee Cheng','local_name'=>'倪(美清)','dob'=>'1918-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Li Chun Huat','local_name'=>'李春发','dob'=>'1941-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Pa Kee Kim','local_name'=>'巴枝金','dob'=>'1939-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Soo Huang','local_name'=>'李素芳','dob'=>'1963-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Gerald Westhoff','local_name'=>'Gerald Westhoff','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Frank Roskam','local_name'=>'Frank Roskam','dob'=>'1961-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Edwald Westhoff','local_name'=>'Edwald Westhoff','dob'=>'1992-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'','local_name'=>'特荷','dob'=>'1996-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Li Chao Chin','local_name'=>'李朝进','dob'=>'1964-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Ong Poh San','local_name'=>'王(寶珊)','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Chew Bee Choo','local_name'=>'周美珠','dob'=>'1976-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Edwin Li','local_name'=>'李特運','dob'=>'1988-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Wendy Eng','local_name'=>'翁雯慈','dob'=>'1989-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Li Han Na','local_name'=>'李韩娜','dob'=>'2017-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Li Yi Yen','local_name'=>'李藝顏','dob'=>'1994-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Lee Chao Ging','local_name'=>'李朝仁','dob'=>'1967-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Tan Pek Kee','local_name'=>'陳碧之','dob'=>'1967-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Lilian Lee','local_name'=>'李立顏','dob'=>'1998-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'','local_name'=>'李朝漢','dob'=>'1983-01-01','chinese_zodiac'=>'豬'],
            ['name'=>'Li Shu Fen','local_name'=>'李素芬','dob'=>'1975-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Choon Siang','local_name'=>'李春祥','dob'=>'1943-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Tan Peik Im','local_name'=>'陈碧音','dob'=>'1946-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'LeeWin Nee','local_name'=>'李云妮','dob'=>'1972-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Khoo Teng Lye','local_name'=>'邱鼎來~云妮','dob'=>'1972-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Khoo Kar Vin','local_name'=>'邱甲運~云妮','dob'=>'1998-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Lee Fong Nee','local_name'=>'李芬妮','dob'=>'1974-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Poh Teik Hooi','local_name'=>'傅徳輝~芬妮','dob'=>'1972-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Poh Sharon','local_name'=>'傅雪倫~芬妮','dob'=>'2003-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Poh Sharmaine','local_name'=>'傅雪敏~芬妮','dob'=>'2006-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Lee Chew Nee','local_name'=>'李秋霓','dob'=>'1975-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Chen Thean Kheng','local_name'=>'曾天靖~秋霓','dob'=>'1973-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Chen Wyman','local_name'=>'曾玮璊~秋霓','dob'=>'2003-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Chen Wylyn','local_name'=>'曾玮淋','dob'=>'2014-01-01','chinese_zodiac'=>'马'],
            ['name'=>'Lee Shao Chou','local_name'=>'李朝慈','dob'=>'1978-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Huang Xiuling','local_name'=>'黃秀玲~朝慈','dob'=>'1979-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Lee Jo Ya','local_name'=>'李卓雅~朝慈','dob'=>'2011-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Jo Sern','local_name'=>'李卓森','dob'=>'2015-01-01','chinese_zodiac'=>'马'],
            ['name'=>'Lee Shao Xian','local_name'=>'李朝贤','dob'=>'1987-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Joo Kin','local_name'=>'李如根','dob'=>'1944-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Lee Joo Eim','local_name'=>'李如音','dob'=>'1946-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Liuy Fong Wing','local_name'=>'廖(芳荣)','dob'=>'1942-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Liuy Boon Chong','local_name'=>'廖(文忠)','dob'=>'1967-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Liuy Boon Kien','local_name'=>'廖文健','dob'=>'1968-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Liuy Lee San','local_name'=>'廖莉珊','dob'=>'1975-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Yu Fei','local_name'=>'李于飞~莉珊','dob'=>'1966-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Lee Wei','local_name'=>'李(威)~莉珊','dob'=>'1998-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Lee Shane','local_name'=>'李軒~莉珊','dob'=>'2001-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Lee Seth','local_name'=>'李智~莉珊','dob'=>'2007-01-01','chinese_zodiac'=>'猪'],
            ['name'=>'Liuy Boon Wei','local_name'=>'廖文偉','dob'=>'1981-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Thor Yin Wei','local_name'=>'涂迎薇~文偉','dob'=>'1984-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Liuy Zi Xing','local_name'=>'廖子欣','dob'=>'2014-01-01','chinese_zodiac'=>'马'],
            ['name'=>'Lee Chun An','local_name'=>'李春安','dob'=>'1948-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Chan Tau Yeak','local_name'=>'詹道月','dob'=>'1957-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Lee Chew Ling','local_name'=>'李秋玲','dob'=>'1977-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Hong Lai Guan','local_name'=>'方來源~秋琳','dob'=>'1976-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Hong Lkye Li','local_name'=>'方恺丽~秋琳','dob'=>'2003-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Hong Jet Li','local_name'=>'方珏利~秋琳','dob'=>'2005-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Lee Chin Hau','local_name'=>'李进豪','dob'=>'1979-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Patcharapom Yamkaew (Jeed)','local_name'=>'Patcharapom Yamkaew (Jeed)','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Lee Wei Hau','local_name'=>'李伟豪','dob'=>'1992-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Lee Joo In','local_name'=>'李如恩','dob'=>'1950-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Sim Peng Keat','local_name'=>'沈炳吉','dob'=>'1949-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Sim Ai Ling','local_name'=>'沈愛玲','dob'=>'1970-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Ang Yam Siang','local_name'=>'洪炎祥','dob'=>'1967-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Ang Xue Li','local_name'=>'洪雪莉','dob'=>'1996-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Sim Ai See','local_name'=>'沈愛絲','dob'=>'1972-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Ng Sang Buo','local_name'=>'黃雙武','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Ng Ker Xin','local_name'=>'黄可欣','dob'=>'1997-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Ng Zheng Hoong','local_name'=>'黄镇鸿','dob'=>'2014-01-01','chinese_zodiac'=>'马'],
            ['name'=>'Sim Ai Tiang','local_name'=>'沈愛珍','dob'=>'1978-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Chua Wee Chuan','local_name'=>'蔡伟川','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Chua Teck Xaun','local_name'=>'蔡德轩','dob'=>'2011-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Choon Kiat ','local_name'=>'李(春吉)','dob'=>'1951-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Wong Siew Hoek','local_name'=>'王秀叶','dob'=>'1957-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Lee Chee Hau','local_name'=>'李志豪','dob'=>'1987-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Cen Ying','local_name'=>'李珍盈','dob'=>'1989-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Lee Chee Lor','local_name'=>'李志乐','dob'=>'1992-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Lee Choon Kheng','local_name'=>'李春慶','dob'=>'1952-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Lee Swee Kim','local_name'=>'李赛琼','dob'=>'1963-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Kai Rong','local_name'=>'李凯龙','dob'=>'1988-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Chai Jee Chen','local_name'=>'蔡宜珍','dob'=>'1989-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Clarisse Lee Xin Tian','local_name'=>'李欣恬','dob'=>'2015-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Arianna Lee Xin Enn','local_name'=>'李欣蒽','dob'=>'2018-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Teresa Lee Ri Sa','local_name'=>'李麗莎','dob'=>'1990-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Lee Kai Shan','local_name'=>'李凯绅','dob'=>'1992-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Lee Chon Chua','local_name'=>'李春泉','dob'=>'1954-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Chuah Suw Ie','local_name'=>'蔡(瑞依)','dob'=>'1955-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Lee Wi Li','local_name'=>'李威勵','dob'=>'1977-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Goh Kooi Bee','local_name'=>'吳桂瑂','dob'=>'1980-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Tan Jenny','local_name'=>'陈洁霓','dob'=>'2002-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Lee Yi Win','local_name'=>'李翊鈗','dob'=>'2012-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Lee Guan Teng','local_name'=>'李冠腾','dob'=>'2015-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Lee Wei Sern','local_name'=>'李威聖','dob'=>'1981-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Wong Yoke Kee','local_name'=>'黄钰淇','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Lee Enya','local_name'=>'李恩雅','dob'=>'2015-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Lee Sue Sern','local_name'=>'李舒嫻','dob'=>'1985-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Lim Chong Liang','local_name'=>'林宗亮','dob'=>'1984-01-01','chinese_zodiac'=>'豬'],
            ['name'=>'Heng Ray','local_name'=>'王磊','dob'=>'2008-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Lim Eason','local_name'=>'林亦善','dob'=>'2012-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Lim Jadson','local_name'=>'林至善','dob'=>'2013-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Lim Qison','local_name'=>'林齐善','dob'=>'2015-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Lee Chong Kuang','local_name'=>'李春光','dob'=>'1955-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Tan Suan Lee','local_name'=>'陈碹莉','dob'=>'1956-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Lee Chia Loon','local_name'=>'李嘉倫','dob'=>'1976-01-01','chinese_zodiac'=>'龍'],
            ['name'=>'Lo Jer Riang','local_name'=>'罗晢亮~嘉倫','dob'=>'1973-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Lo Jay Shung','local_name'=>'罗杰松~嘉倫','dob'=>'2004-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Lo Jay Swin','local_name'=>'罗杰迅~嘉倫','dob'=>'2006-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Lo Jay Cheng','local_name'=>'罗杰诚~嘉倫','dob'=>'2007-01-01','chinese_zodiac'=>'豬'],
            ['name'=>'Lo Jay You','local_name'=>'罗杰友~嘉倫','dob'=>'2009-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'LO Yan Hui','local_name'=>'罗妍荟~嘉倫','dob'=>'2011-01-01','chinese_zodiac'=>'兔'],
            ['name'=>'Lee Jo Anne','local_name'=>'李柔燕','dob'=>'1979-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Chong Chee Chin','local_name'=>'张志进~柔燕','dob'=>'1981-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Daniel Lee Chee Hun','local_name'=>'李吉汉','dob'=>'1982-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Charles Lee Swie Hun','local_name'=>'李瑞漢','dob'=>'1986-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Lee May Chueng','local_name'=>'李媚珺','dob'=>'1989-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Lee Choon Eng','local_name'=>'李春荣','dob'=>'1957-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Patama Chongchiewchanvit','local_name'=>'钟燕芳','dob'=>'1968-01-01','chinese_zodiac'=>'猴'],
            ['name'=>'Peerada Hamsiri','local_name'=>'李嘉娜','dob'=>'2000-01-01','chinese_zodiac'=>''],
            ['name'=>'Natapol Hamsiri','local_name'=>'李韩菲','dob'=>'1989-01-01','chinese_zodiac'=>'蛇'],
            ['name'=>'Boonyalap Hamsiri','local_name'=>'李韩洲','dob'=>'1993-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Boonyahap Sea Lee','local_name'=>'李韩江','dob'=>'1995-01-01','chinese_zodiac'=>'豬'],
            ['name'=>'Thanyapon Sea Lee','local_name'=>'李莉莉','dob'=>'1998-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Lee Chon Kim','local_name'=>'李春锦','dob'=>'1958-01-01','chinese_zodiac'=>'狗'],
            ['name'=>'Ng Lean Choo','local_name'=>'黄莲珠','dob'=>'1960-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Lee Jia Lee','local_name'=>'李嘉麗','dob'=>'1990-01-01','chinese_zodiac'=>'馬'],
            ['name'=>'Chew Ee Siang','local_name'=>'周逸翔','dob'=>'1985-01-01','chinese_zodiac'=>'牛'],
            ['name'=>'Chew Xin Lei','local_name'=>'周芯雷','dob'=>'2015-01-01','chinese_zodiac'=>'羊'],
            ['name'=>'Chew Xin Tian','local_name'=>'周芯恬','dob'=>'2017-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Lee Jia Sen','local_name'=>'李嘉生','dob'=>'1993-01-01','chinese_zodiac'=>'雞'],
            ['name'=>'Lee Joo Ngoh','local_name'=>'李如娥','dob'=>'1960-01-01','chinese_zodiac'=>'鼠'],
            ['name'=>'Xu Chu Hui','local_name'=>'徐初辉','dob'=>'1962-01-01','chinese_zodiac'=>'虎'],
            ['name'=>'Xu Hong Yang','local_name'=>'徐虹洋','dob'=>'2000-01-01','chinese_zodiac'=>'龍'],
    	];
    }
}
